[project]
name = "projeto-databricks-pipeline"
version = "0.1.0"
description = "Aqui vamos a implementar um Pipeline de Engenharia de Dados"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "black>=25.9.0",
]
